ci:
  autofix_prs: false
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [end-of-file-fixer, equirements-txt-fixer]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args:
          [
            --install-types,
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --non-interactive,
            --namespace-packages,
          ]
        additional_dependencies:
          - "pydantic>=2.6.1"
          - "types-protobuf>=4.24.0"
        exclude: ./.*_pb2_.*.py

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        exclude: "^tests/"

  - repo: local
    hooks:
      - id: interrogate
        name: interrogate
        language: system
        entry: interrogate
        types: [python]
        exclude: "setup.py"
        args:
          [--ignore-init-method, --ignore-init-module, -p, -vv, --fail-under=80]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: ["--line-length", "88", "--verbose"]
      - id: ruff-format
        args: ["--verbose"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: ghcr.io/hadolint/hadolint hadolint
        args: ["--ignore", "DL3008", "--ignore", "DL4006"]
