[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
skips = ["B101"]  # optional: skip assert statements

[tool.bandit.assert_used]
skips = ["*_test.py", "test_*.py"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[tool.ruff]
# Enable all rules by default
select = ["ALL"]

# Ignore specific rules
ignore = [
    "D203",  # no-blank-line-before-class
    "D212",  # multi-line-summary-first-line
    "ANN101", # missing-type-self
    "FBT",    # boolean-trap
    "RUF001", # ambiguous-unicode-character-string
]

# Line length
line-length = 100

# Target Python version
target-version = "py39"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/*" = [
    "S101",    # Use of assert detected
    "D100",    # Missing docstring in public module
    "D103",    # Missing docstring in public function
]
